# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-06 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingapply',
            name='incoming_doc_mark',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
